on: 
  workflow_dispatch: {}

jobs:
  trigger-need-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Trigger other workflow
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          # Name or ID of workflow to run
          owner: twunderlich-tc
          workflow_file_name: needTest.yml
          github_token: ${{ secrets.WORKFLOW_KEY }}
          repo: need-test
          ref: main
      - name: run next job
        run: sleep 5s |
            echo "done"
