on: 
  workflow_dispatch: {}

jobs:
  trigger-need-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Trigger other workflow
        id: trigger
        run: exit 1 # bash emptyfile.sh ${{ secrets.WORKFLOW_KEY }}
        continue-on-error: true
      - name: check failure
        if: steps.trigger.outcome != 'success'
        run: |
          echo "failure"
