on: 
  workflow_dispatch: {}

jobs:
  trigger-need-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Trigger other workflow
        run: exit 1 # bash emptyfile.sh ${{ secrets.WORKFLOW_KEY }}
      - name: check failure
        if: ${{ failure() }}
        run: |
          echo "failure"
