on: 
  workflow_dispatch: {}

jobs:
  trigger-need-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Trigger other workflow
        run: bash emptyFile.sh ${{ secrets.BARNDOOR_GITHUB_TOKEN }}
