name: Test need command

on:
  workflow_dispatch:
    inputs:
      input:
        description: 'Directory to deploy'     
        required: false
        default: ""

jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Sleep for 30 seconds
       run: sleep 30s
       shell: bash
     - run: bash emptyfile.sh ${{ github.event.inputs.input }} 
     - run: echo "done"
