name: Test need command

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      input:
        description: 'Directory to deploy'     
        required: false
        default: ""

jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
     - name: Sleep for 30 seconds
       run: sleep 30s
       shell: bash
     - run: echo ${{ github.event.inputs.input }} 
     - run: echo "done"
